### ISSUE TITLE
Get Zillow Regional Home value estimates using API

### ISSUE THREAD

**Issue by adamajm** [codefordurham/affordablehousing_old#11]
Use: http://www.zillow.com/howto/api/GetZestimate.htm

Find out boundaries/number of Durham (and Triangle) "regional ids" as per Zillow

Get "zindexValue" for all of our unique regional IDs. Explore whether you can get historicals index values (back 5 yrs)

Sample API Output
<localRealEstate>
    <region id="271856" type="neighborhood" name="East Queen Anne">
    <zindexValue>525,397</zindexValue>
    <zindexOneYearChange>-0.144</zindexOneYearChange>
    <links>
    <overview>
    http://www.zillow.com/local-info/WA-Seattle/East-Queen-Anne/r_271856/
    </overview>
    <forSaleByOwner>
    http://www.zillow.com/homes/fsbo/East-Queen-Anne-Seattle-WA/
    </forSaleByOwner>
    <forSale>
    http://www.zillow.com/east-queen-anne-seattle-wa/
    </forSale>
    </links>
    </region>

**Comment by trent5995** [comment]
Spent some time poking around on Zillow. Here's the gist of what I found:

Zillow uses its own shapefile for neighborhood boundaries in Raleigh and Charlotte. For Durham it uses zip codes.

Through the api we could access each neighborhood/zip code's zindexValue and 1-year change in zindex value.

Zillow doesn't allow access to estimate data older than a year. You can look at it: there's getChart api that will produce an image file that charts historical property zestimates up to 10 years. But it's an image file not data we could integrate into our site.

Happy to do more exploring if anyone has any questions/ideas.
