### ISSUE TITLE
Initial Style Guide

### ISSUE THREAD

**Issue by ronstebelton** [codefordurham/affordablehousing_old#27]
Create a Style Guide on the github wiki page.  Determine fonts, color scheme, etc.

**Comment by danforthdesign** [comment]
This is kind of jumping the gun. We haven't even figured out the basic layout yet!

**Comment by ronstebelton** [comment]
Obviously, I'm an engineer :)

I added this because as I was making things be more generic, one of the pieces was the color for the graphs that I know you mentioned were not great.  We can adjust any priorities as makes sense.
